// IRB parsing, VC collapsing and the overlap sweep — the three places this
// report can quietly go wrong.

import { strict as assert } from "node:assert";
import test from "node:test";

import { parseIrbConfig, shlexSplit, tokenize, unitSortKey } from "../lib/junos.js";
import { networkDetails } from "../lib/subnet.js";
import tool, { buildSwitchList, irbRowsForSwitch, summarizeNetworks } from "../tools/ip-blocks.js";
import { sheetNamed, stubMist, testCtx } from "./helpers.mjs";

const CONFIG_HQ = [
  "# generated by Mist",
  "set groups top interfaces irb unit 10 description \"Floor 1 Voice\"",
  "set groups top interfaces irb unit 10 family inet address 10.1.10.1/24 primary",
  "set groups top interfaces irb unit 10 family inet address 10.1.10.2/24 preferred vrrp-group 7",
  "set groups top interfaces irb unit 20 family inet address 10.1.20.1/24 virtual-gateway-address 10.1.20.254",
  "set groups top interfaces irb unit 20 disable",
  "set groups top interfaces irb unit 30 family inet dhcp",
  "set groups top interfaces irb unit 40 description 'No address here'",
  "set groups top interfaces irb unit 50 family inet6 address 2001:db8:1::1/64",
  "set groups top vlans voice vlan-id 110",
  "set groups top vlans voice l3-interface irb.10",
  "set groups top vlans data vlan-id 120",
  "set groups top vlans data l3-interface irb.20",
  "set groups top routing-instances VRF-A interface irb.20",
  "delete interfaces irb unit 99",
];

// Overlaps 10.1.10.0/24 from HQ, and duplicates nothing else.
const CONFIG_BRANCH = [
  "set interfaces irb.10 family inet address 10.1.10.5/24",
  "set interfaces irb unit 60 family inet address 10.1.0.1/16",
  "set interfaces irb unit 70 family inet address 192.168.5.1/24",
  "set vlans voice l3-interface irb.10",
  "set vlans voice vlan-id 110",
];

const INVENTORY = [
  { mac: "AABBCC000001", id: "dev-1", name: "hq-sw1", model: "EX4400-48P", serial: "S1", site_id: "s1", connected: true },
  // A two-member virtual chassis: both rows collapse onto the vc_mac.
  { mac: "AABBCC000002", vc_mac: "AABBCC000002", id: "dev-2", name: "br-sw1", model: "EX4100-24T", serial: "S2", site_id: "s2", connected: true },
  { mac: "AABBCC000003", vc_mac: "AABBCC000002", id: "dev-3", name: "br-sw1-member", model: "EX4100-24T", serial: "S3", site_id: "s2" },
  // Unassigned: no site, so no config can be pulled.
  { mac: "AABBCC000009", id: "dev-9", name: "spare-sw", model: "EX2300", serial: "S9" },
];

const SITES = [
  { id: "s1", name: "HQ", address: "1 Main St", country_code: "CA", timezone: "America/Toronto" },
  { id: "s2", name: "Branch", address: "2 Side Rd", country_code: "CA", timezone: "America/Toronto" },
];

const routes = (o = {}) => ({
  "/orgs/org-1/sites": SITES,
  "/orgs/org-1/inventory": INVENTORY,
  "/sites/s1/devices/dev-1/config_cmd": { cli: CONFIG_HQ },
  "/sites/s2/devices/AABBCC000002/config_cmd": { cli: CONFIG_BRANCH },
  "/sites/s2/devices/dev-2/config_cmd": { cli: CONFIG_BRANCH },
  ...o,
});

test("shlexSplit matches Python shlex on quoted Junos descriptions", () => {
  assert.deepEqual(shlexSplit('set x description "Floor 1 Voice"'),
    ["set", "x", "description", "Floor 1 Voice"]);
  assert.deepEqual(shlexSplit("set x description 'Guest Wi-Fi'"),
    ["set", "x", "description", "Guest Wi-Fi"]);
  assert.deepEqual(shlexSplit(String.raw`set x description "quote \" inside"`),
    ["set", "x", "description", 'quote " inside']);
  assert.deepEqual(shlexSplit("a  b   c"), ["a", "b", "c"]);
  assert.deepEqual(shlexSplit(String.raw`back\ slash`), ["back slash"]);
});

test("tokenize falls back to a plain split on an unterminated quote", () => {
  // Python's _tokenize caught shlex's ValueError and did line.split().
  assert.deepEqual(tokenize('set x description "unterminated'),
    ["set", "x", "description", '"unterminated']);
});

test("parseIrbConfig reads units, addresses, flags, VLANs and routing instances", () => {
  const p = parseIrbConfig(CONFIG_HQ);
  assert.deepEqual([...p.units.keys()], ["10", "20", "30", "40", "50"], "delete lines are ignored");

  const u10 = p.units.get("10");
  assert.equal(u10.description, "Floor 1 Voice", "groups top prefix is stripped");
  assert.equal(u10.disabled, false);
  assert.deepEqual([...u10.addresses.values()].map((a) => a.address), ["10.1.10.1/24", "10.1.10.2/24"]);
  assert.deepEqual([...u10.addresses.values()][0].flags, ["primary"]);
  assert.deepEqual([...u10.addresses.values()][1].flags, ["preferred", "vrrp-group 7"]);

  const u20 = p.units.get("20");
  assert.equal(u20.disabled, true);
  assert.deepEqual([...u20.addresses.values()][0].virtual, ["10.1.20.254"]);

  assert.deepEqual(p.units.get("30").dhcp, [["inet", "dhcp"]]);
  assert.equal(p.units.get("40").addresses.size, 0);
  assert.equal([...p.units.get("50").addresses.values()][0].family, "inet6");

  assert.equal(p.vlans.get("voice").vlan_id, "110");
  assert.equal(p.vlans.get("voice").l3_interface, "irb.10");
  assert.equal(p.routingInstances["irb.20"], "VRF-A");
});

test("the irb.N short form is equivalent to `irb unit N`", () => {
  const p = parseIrbConfig(["set interfaces irb.10 family inet address 10.1.10.5/24"]);
  assert.deepEqual([...p.units.keys()], ["10"]);
  assert.equal([...p.units.get("10").addresses.values()][0].address, "10.1.10.5/24");
});

test("unitSortKey puts numeric units in numeric order before named ones", () => {
  assert.deepEqual(["10", "2", "foo", "1"].sort(unitSortKey), ["1", "2", "10", "foo"]);
});

test("buildSwitchList collapses a virtual chassis onto its vc_mac", () => {
  const byId = Object.fromEntries(SITES.map((s) => [s.id, s]));
  const list = buildSwitchList(INVENTORY, byId);
  assert.equal(list.length, 3, "two VC members collapse into one record");

  const vc = list.find((s) => s.mac === "aabbcc000002");
  assert.equal(vc.members, 2);
  assert.equal(vc.name, "br-sw1", "the primary member names the chassis");
  assert.equal(vc.serials, "S2, S3", "every member's serial is kept");
  assert.equal(vc.model, "EX4100-24T", "duplicate models are de-duplicated");
  assert.equal(vc.site_name, "Branch");
  assert.equal(vc.connected, true, "connected if any member is");

  const spare = list.find((s) => s.mac === "aabbcc000009");
  assert.equal(spare.site_id, null);
});

test("buildSwitchList synthesises a device id when the primary row is absent", () => {
  const list = buildSwitchList(
    [{ mac: "AABBCC000011", vc_mac: "AABBCC0000FF", id: "dev-x", site_id: "s1" }],
    {},
  );
  assert.equal(list[0].device_id, "00000000-0000-0000-1000-aabbcc0000ff");
});

test("irbRowsForSwitch emits one row per address, plus dhcp and empty units", () => {
  const sw = {
    site_name: "HQ", name: "hq-sw1", mac: "aabbcc000001", model: "EX4400-48P",
    site_id: "s1", device_id: "dev-1",
  };
  const rows = irbRowsForSwitch(sw, parseIrbConfig(CONFIG_HQ));

  // unit 10 -> 2 static, 20 -> 1 static, 30 -> 1 dhcp, 40 -> 1 none, 50 -> 1 static
  assert.equal(rows.length, 6);

  const first = rows[0];
  assert.equal(first.Interface, "irb.10");
  assert.equal(first["VLAN Name"], "voice");
  assert.equal(first["VLAN ID"], 110, "a numeric VLAN id becomes a number");
  assert.equal(first.Family, "IPv4");
  assert.equal(first["Address Type"], "static");
  assert.equal(first.Network, "10.1.10.0/24");
  assert.equal(first["Subnet Mask"], "255.255.255.0");
  assert.equal(first.Broadcast, "10.1.10.255");
  assert.equal(first["Usable Hosts"], 254);
  assert.equal(first.Flags, "primary");

  const disabled = rows.find((r) => r.Interface === "irb.20");
  assert.equal(disabled.Flags, "disabled", "a disabled unit flags every one of its addresses");
  assert.equal(disabled["Virtual / VRRP Address"], "10.1.20.254");
  assert.equal(disabled["Routing Instance"], "VRF-A");

  const dhcp = rows.find((r) => r["Address Type"] === "dhcp");
  assert.equal(dhcp.Notes, "Address assigned dynamically; not in config");

  const none = rows.find((r) => r["Address Type"] === "none");
  assert.equal(none.Interface, "irb.40");
  assert.equal(none.Notes, "IRB unit has no address configured");

  const v6 = rows.find((r) => r.Family === "IPv6");
  assert.equal(v6.Network, "2001:db8:1::/64");
  assert.equal(v6.Broadcast, "n/a (IPv6)");
});

test("summarizeNetworks aggregates per network and flags multi-site reuse", () => {
  const mk = (site, sw, addr, vlan) => {
    const d = networkDetails(addr);
    return {
      Site: site, Switch: sw, "Site ID": "", "VLAN ID": vlan, "VLAN Name": "voice",
      "Routing Instance": "", "IP Address": d["IP Address"], _network: d._network,
    };
  };
  const { rows, overlapCount } = summarizeNetworks([
    mk("HQ", "hq-sw1", "10.1.10.1/24", 110),
    mk("Branch", "br-sw1", "10.1.10.5/24", 110),
    mk("Branch", "br-sw1", "192.168.5.1/24", 150),
  ]);

  const shared = rows.find((r) => r.Network === "10.1.10.0/24");
  assert.equal(shared["Interface Count"], 2);
  assert.equal(shared["Switch Count"], 2);
  assert.equal(shared["Site Count"], 2);
  assert.equal(shared["Seen At Multiple Sites"], "Yes");
  assert.equal(shared.Sites, "Branch, HQ");
  assert.equal(shared["Interface IPs"], "10.1.10.1, 10.1.10.5");

  const solo = rows.find((r) => r.Network === "192.168.5.0/24");
  assert.equal(solo["Seen At Multiple Sites"], "No");
  assert.equal(overlapCount, 0, "two /24s that are equal are the same network, not an overlap");
});

test("summarizeNetworks finds a nested block as an overlap both ways", () => {
  const mk = (addr) => {
    const d = networkDetails(addr);
    return { Site: "HQ", Switch: "sw", "Site ID": "", "VLAN ID": "", "VLAN Name": "", "Routing Instance": "", "IP Address": d["IP Address"], _network: d._network };
  };
  const { rows, overlapCount } = summarizeNetworks([
    mk("10.1.0.1/16"), mk("10.1.10.1/24"), mk("192.168.5.1/24"),
  ]);
  assert.equal(overlapCount, 2, "the /16 and the /24 inside it");
  assert.equal(rows.find((r) => r.Network === "10.1.0.0/16")["Overlaps With"], "10.1.10.0/24");
  assert.equal(rows.find((r) => r.Network === "10.1.10.0/24")["Overlaps With"], "10.1.0.0/16");
  assert.equal(rows.find((r) => r.Network === "192.168.5.0/24")["Overlaps With"], "");
});

test("link-local networks are left out of the overlap sweep", () => {
  const mk = (addr) => {
    const d = networkDetails(addr);
    return { Site: "HQ", Switch: "sw", "Site ID": "", "VLAN ID": "", "VLAN Name": "", "Routing Instance": "", "IP Address": d["IP Address"], _network: d._network };
  };
  const { overlapCount } = summarizeNetworks([mk("fe80::1/10"), mk("fe80::2/64")]);
  assert.equal(overlapCount, 0);
});

test("the tool produces all five sheets with the Python's columns", async () => {
  stubMist(routes());
  const result = await tool.run(testCtx());
  assert.deepEqual(result.sheets.map((s) => s.name),
    ["Summary", "IRB Interfaces", "Networks", "Switches", "Sites"]);
  assert.equal(sheetNamed(result, "IRB Interfaces").columns.length, 27);
  assert.equal(sheetNamed(result, "Networks").columns.length, 16);
  assert.equal(sheetNamed(result, "Switches").columns.length, 14);
  assert.equal(sheetNamed(result, "Sites").columns.length, 7);
  assert.match(result.filename, /^mist_irb_Acme_Corp_\d{8}_\d{6}\.xlsx$/);
});

test("an unassigned switch is reported, not silently dropped", async () => {
  stubMist(routes());
  const result = await tool.run(testCtx());
  const spare = sheetNamed(result, "Switches").rows.find((r) => r.Switch === "spare-sw");
  assert.equal(spare["Config Status"], "Skipped - not assigned to a site");
  assert.equal(spare["Site ID"], "");
});

test("a switch whose config fails is recorded with its error", async () => {
  stubMist(routes({
    "/sites/s1/devices/dev-1/config_cmd": () => { throw new Error("boom"); },
  }));
  const result = await tool.run(testCtx());
  const hq = sheetNamed(result, "Switches").rows.find((r) => r.Switch === "hq-sw1");
  assert.equal(hq["Config Status"], "Error");
  assert.match(hq.Error, /Could not reach the Mist API|boom/);
  // The other switch still reports.
  assert.ok(sheetNamed(result, "IRB Interfaces").rows.length > 0);
});

test("a switch returning no config is distinguished from one with no IRBs", async () => {
  stubMist(routes({ "/sites/s1/devices/dev-1/config_cmd": { cli: [] } }));
  const result = await tool.run(testCtx());
  const hq = sheetNamed(result, "Switches").rows.find((r) => r.Switch === "hq-sw1");
  assert.equal(hq["Config Status"], "No config returned");
  assert.equal(hq["Config Lines"], 0);
});

test("a config returned as one string is split into lines", async () => {
  stubMist(routes({ "/sites/s1/devices/dev-1/config_cmd": { cli: CONFIG_HQ.join("\n") } }));
  const result = await tool.run(testCtx());
  const hq = sheetNamed(result, "Switches").rows.find((r) => r.Switch === "hq-sw1");
  assert.equal(hq["IRB Units"], 5);
});

test("the Summary sheet counts what the Python counted", async () => {
  stubMist(routes());
  const result = await tool.run(testCtx());
  const get = (item) => sheetNamed(result, "Summary").rows.find((r) => r.Item === item)?.Value;
  assert.equal(get("Org"), "Acme Corp");
  assert.equal(get("Sites"), 2);
  assert.equal(get("Switches / VCs"), 3);
  assert.equal(get("Switches not assigned to a site"), 1);
  assert.equal(get("IPv6 addresses"), 1);
  assert.ok(Number(get("IRB static addresses")) >= 5);
  // The Branch /16 contains both HQ /24s, so three networks are implicated.
  assert.equal(get("Networks overlapping another network"), 3,
    "10.1.0.0/16 plus the 10.1.10.0/24 and 10.1.20.0/24 inside it");
  assert.equal(get("Unique networks"), 5);
});

test("saveConfigs produces one downloadable .txt per switch", async () => {
  stubMist(routes());
  const off = await tool.run(testCtx());
  assert.deepEqual(off.files, []);

  const on = await tool.run(testCtx({ params: { saveConfigs: true } }));
  assert.equal(on.files.length, 2);
  assert.ok(on.files.every((f) => /\.txt$/.test(f.name)));
  assert.ok(on.files.some((f) => f.name === "HQ__hq-sw1__aabbcc000001.txt"));
});
