// Subnet math parity.
//
// The fixture below was generated by Python's own ipaddress module (the exact
// library mist_ip_blocks.py used) and frozen here, so the port stays provably
// identical without needing Python at test time.
//
// Regenerate with:
//   python3 -c "import ipaddress,json;print(json.dumps({c:{...} for c in cases}))"

import { strict as assert } from "node:assert";
import test from "node:test";

import {
  AddrError, formatAddr, ipInterface, isLinkLocal, networkDetails, overlaps, parseAddr,
} from "../lib/subnet.js";

const PY = {
  "10.1.1.1/24": {
    "ip": "10.1.1.1",
    "prefixlen": 24,
    "network": "10.1.1.0/24",
    "network_address": "10.1.1.0",
    "broadcast_address": "10.1.1.255",
    "netmask": "255.255.255.0",
    "hostmask": "0.0.0.255",
    "num_addresses": "256",
    "is_link_local": false
  },
  "192.168.0.5/30": {
    "ip": "192.168.0.5",
    "prefixlen": 30,
    "network": "192.168.0.4/30",
    "network_address": "192.168.0.4",
    "broadcast_address": "192.168.0.7",
    "netmask": "255.255.255.252",
    "hostmask": "0.0.0.3",
    "num_addresses": "4",
    "is_link_local": false
  },
  "172.16.5.1/31": {
    "ip": "172.16.5.1",
    "prefixlen": 31,
    "network": "172.16.5.0/31",
    "network_address": "172.16.5.0",
    "broadcast_address": "172.16.5.1",
    "netmask": "255.255.255.254",
    "hostmask": "0.0.0.1",
    "num_addresses": "2",
    "is_link_local": false
  },
  "10.0.0.7/32": {
    "ip": "10.0.0.7",
    "prefixlen": 32,
    "network": "10.0.0.7/32",
    "network_address": "10.0.0.7",
    "broadcast_address": "10.0.0.7",
    "netmask": "255.255.255.255",
    "hostmask": "0.0.0.0",
    "num_addresses": "1",
    "is_link_local": false
  },
  "10.0.0.0/24": {
    "ip": "10.0.0.0",
    "prefixlen": 24,
    "network": "10.0.0.0/24",
    "network_address": "10.0.0.0",
    "broadcast_address": "10.0.0.255",
    "netmask": "255.255.255.0",
    "hostmask": "0.0.0.255",
    "num_addresses": "256",
    "is_link_local": false
  },
  "10.0.0.255/24": {
    "ip": "10.0.0.255",
    "prefixlen": 24,
    "network": "10.0.0.0/24",
    "network_address": "10.0.0.0",
    "broadcast_address": "10.0.0.255",
    "netmask": "255.255.255.0",
    "hostmask": "0.0.0.255",
    "num_addresses": "256",
    "is_link_local": false
  },
  "169.254.1.1/16": {
    "ip": "169.254.1.1",
    "prefixlen": 16,
    "network": "169.254.0.0/16",
    "network_address": "169.254.0.0",
    "broadcast_address": "169.254.255.255",
    "netmask": "255.255.0.0",
    "hostmask": "0.0.255.255",
    "num_addresses": "65536",
    "is_link_local": true
  },
  "0.0.0.0/0": {
    "ip": "0.0.0.0",
    "prefixlen": 0,
    "network": "0.0.0.0/0",
    "network_address": "0.0.0.0",
    "broadcast_address": "255.255.255.255",
    "netmask": "0.0.0.0",
    "hostmask": "255.255.255.255",
    "num_addresses": "4294967296",
    "is_link_local": false
  },
  "255.255.255.255/32": {
    "ip": "255.255.255.255",
    "prefixlen": 32,
    "network": "255.255.255.255/32",
    "network_address": "255.255.255.255",
    "broadcast_address": "255.255.255.255",
    "netmask": "255.255.255.255",
    "hostmask": "0.0.0.0",
    "num_addresses": "1",
    "is_link_local": false
  },
  "2001:db8::1/64": {
    "ip": "2001:db8::1",
    "prefixlen": 64,
    "network": "2001:db8::/64",
    "network_address": "2001:db8::",
    "broadcast_address": "2001:db8::ffff:ffff:ffff:ffff",
    "netmask": "ffff:ffff:ffff:ffff::",
    "hostmask": "::ffff:ffff:ffff:ffff",
    "num_addresses": "18446744073709551616",
    "is_link_local": false
  },
  "fe80::1/10": {
    "ip": "fe80::1",
    "prefixlen": 10,
    "network": "fe80::/10",
    "network_address": "fe80::",
    "broadcast_address": "febf:ffff:ffff:ffff:ffff:ffff:ffff:ffff",
    "netmask": "ffc0::",
    "hostmask": "3f:ffff:ffff:ffff:ffff:ffff:ffff:ffff",
    "num_addresses": "332306998946228968225951765070086144",
    "is_link_local": true
  },
  "::1/128": {
    "ip": "::1",
    "prefixlen": 128,
    "network": "::1/128",
    "network_address": "::1",
    "broadcast_address": "::1",
    "netmask": "ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff",
    "hostmask": "::",
    "num_addresses": "1",
    "is_link_local": false
  },
  "2001:db8:0:0:1::/80": {
    "ip": "2001:db8:0:0:1::",
    "prefixlen": 80,
    "network": "2001:db8:0:0:1::/80",
    "network_address": "2001:db8:0:0:1::",
    "broadcast_address": "2001:db8::1:ffff:ffff:ffff",
    "netmask": "ffff:ffff:ffff:ffff:ffff::",
    "hostmask": "::ffff:ffff:ffff",
    "num_addresses": "281474976710656",
    "is_link_local": false
  },
  "::ffff:192.0.2.1/96": {
    "ip": "::ffff:c000:201",
    "prefixlen": 96,
    "network": "::ffff:0:0/96",
    "network_address": "::ffff:0:0",
    "broadcast_address": "::ffff:ffff:ffff",
    "netmask": "ffff:ffff:ffff:ffff:ffff:ffff::",
    "hostmask": "::ffff:ffff",
    "num_addresses": "4294967296",
    "is_link_local": false
  },
  "2001:0db8:85a3:0000:0000:8a2e:0370:7334/56": {
    "ip": "2001:db8:85a3::8a2e:370:7334",
    "prefixlen": 56,
    "network": "2001:db8:85a3::/56",
    "network_address": "2001:db8:85a3::",
    "broadcast_address": "2001:db8:85a3:ff:ffff:ffff:ffff:ffff",
    "netmask": "ffff:ffff:ffff:ff00::",
    "hostmask": "::ff:ffff:ffff:ffff:ffff",
    "num_addresses": "4722366482869645213696",
    "is_link_local": false
  },
  "fd00::/8": {
    "ip": "fd00::",
    "prefixlen": 8,
    "network": "fd00::/8",
    "network_address": "fd00::",
    "broadcast_address": "fdff:ffff:ffff:ffff:ffff:ffff:ffff:ffff",
    "netmask": "ff00::",
    "hostmask": "ff:ffff:ffff:ffff:ffff:ffff:ffff:ffff",
    "num_addresses": "1329227995784915872903807060280344576",
    "is_link_local": false
  },
  "2001:db8::/126": {
    "ip": "2001:db8::",
    "prefixlen": 126,
    "network": "2001:db8::/126",
    "network_address": "2001:db8::",
    "broadcast_address": "2001:db8::3",
    "netmask": "ffff:ffff:ffff:ffff:ffff:ffff:ffff:fffc",
    "hostmask": "::3",
    "num_addresses": "4",
    "is_link_local": false
  }
};

test("ipInterface matches Python's ipaddress field for field", () => {
  for (const [cidr, e] of Object.entries(PY)) {
    const i = ipInterface(cidr);
    const f = (v) => formatAddr(i.version, v);
    assert.equal(i.ipStr, e.ip, `${cidr} ip`);
    assert.equal(i.prefixlen, e.prefixlen, `${cidr} prefixlen`);
    assert.equal(i.networkStr, e.network, `${cidr} network`);
    assert.equal(f(i.networkAddress), e.network_address, `${cidr} network_address`);
    assert.equal(f(i.broadcastAddress), e.broadcast_address, `${cidr} broadcast_address`);
    assert.equal(f(i.netmask), e.netmask, `${cidr} netmask`);
    assert.equal(f(i.hostmask), e.hostmask, `${cidr} hostmask`);
    assert.equal(i.numAddresses.toString(), e.num_addresses, `${cidr} num_addresses`);
    assert.equal(isLinkLocal(i.version, i.ip), e.is_link_local, `${cidr} is_link_local`);
  }
});

test("IPv6 is held as BigInt, so a /64 does not lose precision", () => {
  const a = ipInterface("2001:db8::/64");
  assert.equal(typeof a.numAddresses, "bigint");
  assert.equal(a.numAddresses, 18446744073709551616n);
  // The overlap sweep compares these directly; Number would collapse them.
  const b = ipInterface("2001:db8:0:0:8000::/65");
  assert.notEqual(a.networkAddress, b.networkAddress - 1n);
  assert.ok(overlaps(a, b), "a /65 sits inside its /64");
});

test("networkDetails reproduces the /30, /31 and /32 special cases", () => {
  const thirty = networkDetails("192.168.0.5/30");
  assert.equal(thirty.Broadcast, "192.168.0.7");
  assert.equal(thirty["First Usable"], "192.168.0.5");
  assert.equal(thirty["Last Usable"], "192.168.0.6");
  assert.equal(thirty["Usable Hosts"], 2);

  const p31 = networkDetails("172.16.5.1/31");
  assert.equal(p31.Broadcast, "n/a (/31)");
  assert.equal(p31["First Usable"], "172.16.5.0");
  assert.equal(p31["Last Usable"], "172.16.5.1");
  assert.equal(p31["Usable Hosts"], 2);

  const p32 = networkDetails("10.0.0.7/32");
  assert.equal(p32.Broadcast, "n/a (/32)");
  assert.equal(p32["First Usable"], "10.0.0.7");
  assert.equal(p32["Usable Hosts"], 1);
});

test("networkDetails flags an address that is the network or broadcast", () => {
  assert.deepEqual(networkDetails("10.0.0.0/24")._notes, ["IP is the network address"]);
  assert.deepEqual(networkDetails("10.0.0.255/24")._notes, ["IP is the broadcast address"]);
  assert.deepEqual(networkDetails("10.0.0.9/24")._notes, []);
  assert.deepEqual(networkDetails("fe80::1/64")._notes, ["Link-local"]);
});

test("IPv6 usable hosts switch to exponent form past 2^32", () => {
  assert.equal(networkDetails("2001:db8::/96")["Usable Hosts"], 4294967296);
  assert.equal(networkDetails("2001:db8::/64")["Usable Hosts"], "2^64");
  assert.equal(networkDetails("2001:db8::/126").Broadcast, "n/a (IPv6)");
});

test("an unparseable address is reported, not thrown", () => {
  const d = networkDetails("not-an-address/24");
  assert.match(d.Notes, /Unparseable address/);
  assert.equal(d._network, undefined);
});

test("IPv6 text forms round-trip the way Python prints them", () => {
  const round = (s) => {
    const { version, value } = parseAddr(s);
    return formatAddr(version, value);
  };
  assert.equal(round("2001:0db8:0000:0000:0000:0000:0000:0001"), "2001:db8::1");
  assert.equal(round("::"), "::");
  assert.equal(round("::1"), "::1");
  assert.equal(round("fe80::1%eth0"), "fe80::1", "a zone id is dropped");
  assert.equal(round("::ffff:192.0.2.1"), "::ffff:c000:201", "embedded IPv4 expands");
  assert.equal(round("2001:db8:0:1:1:1:1:1"), "2001:db8:0:1:1:1:1:1", "a single zero is not compressed");
});

test("malformed addresses raise AddrError", () => {
  for (const bad of ["10.0.0.256", "10.0.0", "1::2::3", "2001:db8:::1", "10.0.0.1/33", "zz::1"]) {
    assert.throws(() => parseAddr(bad.split("/")[0]) && ipInterface(bad), AddrError, bad);
  }
});

test("overlaps only compares like versions", () => {
  const a = ipInterface("10.0.0.0/8");
  const b = ipInterface("10.1.0.0/16");
  const c = ipInterface("192.168.0.0/16");
  assert.ok(overlaps(a, b));
  assert.ok(!overlaps(a, c));
  assert.ok(!overlaps(a, ipInterface("2001:db8::/32")), "v4 and v6 never overlap");
});
